const routes = [
  // -- APPEND ROUTES HERE --
  {
    id: "maxHeight",
    path: "/max-height",
    exact: true,
    component: () => import("pages/MaxHeight"),
  },
  {
    id: "minHeight",
    path: "/min-height",
    exact: true,
    component: () => import("pages/MinHeight"),
  },
  {
    id: "height",
    path: "/height",
    exact: true,
    component: () => import("pages/Height"),
  },
  {
    id: "maxWidth",
    path: "/max-width",
    exact: true,
    component: () => import("pages/MaxWidth"),
  },
  {
    id: "minWidth",
    path: "/min-width",
    exact: true,
    component: () => import("pages/MinWidth"),
  },
  {
    id: "width",
    path: "/width",
    exact: true,
    component: () => import("pages/Width"),
  },
  {
    id: "spaceBetween",
    path: "/space-between",
    exact: true,
    component: () => import("pages/SpaceBetween"),
  },
  {
    id: "margin",
    path: "/margin",
    exact: true,
    component: () => import("pages/Margin"),
  },
  {
    id: "padding",
    path: "/padding",
    exact: true,
    component: () => import("pages/Padding"),
  },
  {
    id: "placeSelf",
    path: "/place-self",
    exact: true,
    component: () => import("pages/PlaceSelf"),
  },
  {
    id: "placeItems",
    path: "/place-items",
    exact: true,
    component: () => import("pages/PlaceItems"),
  },
  {
    id: "placeContent",
    path: "/place-content",
    exact: true,
    component: () => import("pages/PlaceContent"),
  },
  {
    id: "alignSelf",
    path: "/align-self",
    exact: true,
    component: () => import("pages/AlignSelf"),
  },
  {
    id: "alignItems",
    path: "/align-items",
    exact: true,
    component: () => import("pages/AlignItems"),
  },
  {
    id: "alignContent",
    path: "/align-content",
    exact: true,
    component: () => import("pages/AlignContent"),
  },
  {
    id: "justifySelf",
    path: "/justify-self",
    exact: true,
    component: () => import("pages/JustifySelf"),
  },
  {
    id: "justifyItems",
    path: "/justify-items",
    exact: true,
    component: () => import("pages/JustifyItems"),
  },
  {
    id: "justifyContent",
    path: "/justify-content",
    exact: true,
    component: () => import("pages/JustifyContent"),
  },
  {
    id: "gap",
    path: "/gap",
    exact: true,
    component: () => import("pages/Gap"),
  },
  {
    id: "gridAutoFlow",
    path: "/grid-auto-flow",
    exact: true,
    component: () => import("pages/GridAutoFlow"),
  },
  {
    id: "gridRowStartEnd",
    path: "/grid-row-start-end",
    exact: true,
    component: () => import("pages/GridRowStartEnd"),
  },
  {
    id: "gridTemplateRows",
    path: "/grid-template-rows",
    exact: true,
    component: () => import("pages/GridTemplateRows"),
  },
  {
    id: "gridColumnStartEnd",
    path: "/grid-column-start-end",
    exact: true,
    component: () => import("pages/GridColumnStartEnd"),
  },
  {
    id: "gridTemplateColumns",
    path: "/grid-template-columns",
    exact: true,
    component: () => import("pages/GridTemplateColumns"),
  },
  {
    id: "order",
    path: "/order",
    exact: true,
    component: () => import("pages/Order"),
  },
  {
    id: "flexShrink",
    path: "/flex-shrink",
    exact: true,
    component: () => import("pages/FlexShrink"),
  },
  {
    id: "flexGrow",
    path: "/flex-grow",
    exact: true,
    component: () => import("pages/FlexGrow"),
  },
  {
    id: "flex",
    path: "/flex",
    exact: true,
    component: () => import("pages/Flex"),
  },
  {
    id: "flexWrap",
    path: "/flex-wrap",
    exact: true,
    component: () => import("pages/FlexWrap"),
  },
  {
    id: "flexDirection",
    path: "/flex-direction",
    exact: true,
    component: () => import("pages/FlexDirection"),
  },
  {
    id: "zIndex",
    path: "/z-index",
    exact: true,
    component: () => import("pages/ZIndex"),
  },
  {
    id: "visibility",
    path: "/visibility",
    exact: true,
    component: () => import("pages/Visibility"),
  },
  {
    id: "topRightBottomLeft",
    path: "/top-right-bottom-left",
    exact: true,
    component: () => import("pages/TopRightBottomLeft"),
  },
  {
    id: "position",
    path: "/position",
    exact: true,
    component: () => import("pages/Position"),
  },
  {
    id: "overscrollBehavior",
    path: "/overscroll-behavior",
    exact: true,
    component: () => import("pages/OverscrollBehavior"),
  },
  {
    id: "overflow",
    path: "/overflow",
    exact: true,
    component: () => import("pages/Overflow"),
  },
  {
    id: "objectPosition",
    path: "/object-position",
    exact: true,
    component: () => import("pages/ObjectPosition"),
  },
  {
    id: "objectFit",
    path: "/object-fit",
    exact: true,
    component: () => import("pages/ObjectFit"),
  },
  {
    id: "clear",
    path: "/clear",
    exact: true,
    component: () => import("pages/Clear"),
  },
  {
    id: "floats",
    path: "/floats",
    exact: true,
    component: () => import("pages/Floats"),
  },
  {
    id: "display",
    path: "/display",
    exact: true,
    component: () => import("pages/Display"),
  },
  {
    id: "boxSizing",
    path: "/box-sizing",
    exact: true,
    component: () => import("pages/BoxSizing"),
  },
  {
    id: "home",
    path: "/",
    exact: true,
    component: () => import("pages/Home"),
  },
  {
    id: "404",
    path: "*",
    exact: false,
    component: () => import("pages/404"),
  },
];

export default routes;
