const variants = {
  accessibility: ["responsive", "focus", "focus-within"],
  alignContent: ["responsive"],
  alignItems: ["responsive"],
  alignSelf: ["responsive"],
  appearance: ["responsive"],
  aspect: ["responsive", "hover", "focus"],
  backgroundAttachment: ["responsive"],
  backgroundClip: ["responsive"],
  backgroundColor: [
    "responsive",
    "hover",
    "group-hover",
    "focus",
    "focus-within",
  ],
  backgroundImage: ["responsive"],
  backgroundOpacity: [
    "responsive",
    "hover",
    "group-hover",
    "focus",
    "focus-within",
  ],
  backgroundOrigin: ["responsive"],
  backgroundPosition: ["responsive"],
  backgroundRepeat: ["responsive"],
  backgroundSize: ["responsive"],
  blur: ["responsive", "hover", "group-hover", "focus", "focus-within"],
  borderCollapse: ["responsive"],
  borderColor: ["responsive", "hover", "group-hover", "focus", "focus-within"],
  borderOpacity: [
    "responsive",
    "hover",
    "group-hover",
    "focus",
    "focus-within",
  ],
  borderRadius: ["responsive"],
  borderStyle: ["responsive"],
  borderWidth: ["responsive"],
  boxDecorationBreak: ["responsive"],
  boxShadow: ["responsive", "hover", "group-hover", "focus", "focus-within"],
  boxSizing: ["responsive"],
  brightness: ["responsive", "hover", "group-hover", "focus", "focus-within"],
  clear: ["responsive"],
  cursor: ["responsive"],
  display: ["responsive"],
  divideColor: ["responsive"],
  divideOpacity: ["responsive"],
  divideStyle: ["responsive"],
  divideWidth: ["responsive"],
  fill: ["responsive", "hover", "focus"],
  flex: ["responsive"],
  flexDirection: ["responsive"],
  flexBasis: ["responsive", "hover", "focus"],
  flexGrow: ["responsive"],
  flexShrink: ["responsive"],
  flexWrap: ["responsive"],
  float: ["responsive"],
  fontSize: ["responsive"],
  fontSmoothing: ["responsive"],
  fontStyle: ["responsive"],
  fontVariantNumeric: ["responsive"],
  fontWeight: ["responsive"],
  gap: ["responsive"],
  gradientColorStops: ["responsive", "hover", "focus"],
  gridAutoColumns: ["responsive"],
  gridAutoFlow: ["responsive"],
  gridAutoRows: ["responsive"],
  gridColumn: ["responsive"],
  gridColumnEnd: ["responsive"],
  gridColumnStart: ["responsive"],
  gridRow: ["responsive"],
  gridRowEnd: ["responsive"],
  gridRowStart: ["responsive"],
  gridTemplateColumns: ["responsive"],
  gridTemplateRows: ["responsive"],
  height: ["responsive"],
  hyphens: ["responsive"],
  inset: ["responsive"],
  isolation: ["responsive"],
  justifyContent: ["responsive"],
  justifyItems: ["responsive"],
  justifySelf: ["responsive"],
  letterSpacing: ["responsive"],
  lineClamp: ["responsive"],
  lineHeight: ["responsive"],
  listStylePosition: ["responsive"],
  listStyleType: ["responsive"],
  margin: ["responsive"],
  maxHeight: ["responsive"],
  maxWidth: ["responsive"],
  minHeight: ["responsive"],
  minWidth: ["responsive"],
  mixBlendMode: ["responsive"],
  objectFit: ["responsive"],
  objectPosition: ["responsive"],
  opacity: ["responsive", "hover", "group-hover", "focus", "focus-within"],
  order: ["responsive"],
  outlineColor: ["responsive", "focus", "focus-within"],
  outlineOffset: ["responsive", "focus", "focus-within"],
  outlineOpacity: ["responsive", "focus", "focus-within"],
  outlineStyle: ["responsive", "focus", "focus-within"],
  outlineWidth: ["responsive", "focus", "focus-within"],
  overflow: ["responsive"],
  overscrollBehavior: ["responsive"],
  padding: ["responsive"],
  placeContent: ["responsive"],
  placeItems: ["responsive"],
  placeSelf: ["responsive"],
  placeholderColor: ["responsive", "focus"],
  placeholderOpacity: ["responsive", "focus"],
  pointerEvents: ["responsive"],
  position: ["responsive"],
  resize: ["responsive"],
  ringColor: ["responsive", "focus", "focus-within"],
  ringOffsetColor: ["responsive", "focus", "focus-within"],
  ringOffsetWidth: ["responsive", "focus", "focus-within"],
  ringOpacity: ["responsive", "focus", "focus-within"],
  ringWidth: ["responsive", "focus", "focus-within"],
  rotate: ["responsive", "hover", "focus"],
  scale: ["responsive", "hover", "focus"],
  size: ["responsive"],
  skew: ["responsive", "hover", "focus"],
  space: ["responsive"],
  stroke: ["responsive", "hover", "focus"],
  strokeWidth: ["responsive", "hover", "focus"],
  tableLayout: ["responsive"],
  textAlign: ["responsive"],
  textColor: ["responsive", "hover", "group-hover", "focus", "focus-within"],
  textDecoration: ["responsive", "focus", "focus-within", "hover"],
  textDecorationColor: ["responsive", "focus", "focus-within", "hover"],
  textDecorationStyle: ["responsive", "focus", "focus-within", "hover"],
  textDecorationThickness: ["responsive", "focus", "focus-within", "hover"],
  textIndent: ["responsive"],
  textOpacity: ["responsive", "hover", "group-hover", "focus", "focus-within"],
  textOverflow: ["responsive"],
  textTransform: ["responsive"],
  textUnderlineOffset: ["responsive"],
  textWrap: ["responsive"],
  transformOrigin: ["responsive"],
  translate: ["responsive", "hover", "focus"],
  userSelect: ["responsive"],
  verticalAlign: ["responsive"],
  visibility: ["responsive"],
  whitespace: ["responsive"],
  width: ["responsive"],
  wordBreak: ["responsive"],
  zIndex: ["responsive", "focus", "focus-within"],
};

export default variants;
