import generateAlign from "./align";
import generateBase from "./base";
import generateBg from "./bg";
import generateBorder from "./border";
import generateBox from "./box";
import generateClear from "./clear";
import generateContainer from "./container";
import generateDisplay from "./display";
import generateDivide from "./divide";
import generateFlex from "./flex";
import generateFloat from "./float";
import generateForm from "./form";
import generateGradient from "./gradient";
import generateGrid from "./grid";
import generateHeight from "./height";
import generateInteractivity from "./interactivity";
import generateJustify from "./justify";
import generateLeading from "./leading";
import generateList from "./list";
import generateMargin from "./margin";
import generateObject from "./object";
import generateOpacity from "./opacity";
import generateOverflow from "./overflow";
import generateOverscroll from "./overscroll";
import generatePadding from "./padding";
import generatePlace from "./place";
import generatePlaceholder from "./placeholder";
import generatePosition from "./position";
import generateShadow from "./shadow";
import generateSpace from "./space";
import generateTable from "./table";
import generateText from "./text";
import generateTracking from "./tracking";
import generateVisibility from "./visibility";
import generateWidth from "./width";
import generateZIndex from "./zindex";

const generateTailwindCss = (configOptions = {}) => {
  generateAlign(configOptions);
  generateBase(configOptions);
  generateBg(configOptions);
  generateBorder(configOptions);
  generateBox(configOptions);
  generateClear(configOptions);
  generateContainer(configOptions);
  generateDisplay(configOptions);
  generateDivide(configOptions);
  generateFlex(configOptions);
  generateFloat(configOptions);
  generateForm(configOptions);
  generateGradient(configOptions);
  generateGrid(configOptions);
  generateHeight(configOptions);
  generateInteractivity(configOptions);
  generateJustify(configOptions);
  generateLeading(configOptions);
  generateList(configOptions);
  generateMargin(configOptions);
  generateObject(configOptions);
  generateOpacity(configOptions);
  generateOverflow(configOptions);
  generateOverscroll(configOptions);
  generatePadding(configOptions);
  generatePlace(configOptions);
  generatePlaceholder(configOptions);
  generatePosition(configOptions);
  generateShadow(configOptions);
  generateSpace(configOptions);
  generateTable(configOptions);
  generateText(configOptions);
  generateTracking(configOptions);
  generateVisibility(configOptions);
  generateWidth(configOptions);
  generateZIndex(configOptions);
};

export default generateTailwindCss;
