const menus = [
  {
    title: "Layout",
    items: [
      { label: "Box Decoration Break" },
      { label: "Box Sizing" },
      { label: "Display" },
      { label: "Floats" },
      { label: "Clear" },
      { label: "Object Fit" },
      { label: "Object Position" },
      { label: "Overflow" },
      { label: "Overscroll Behavior" },
      { label: "Position" },
      { label: "Top / Right / Bottom / Left" },
      { label: "Visibility" },
      { label: "Z-Index" },
    ],
  },
  {
    title: "Flexbox & Grid",
    items: [
      { label: "Flex Basis" },
      { label: "Flex Direction" },
      { label: "Flex Wrap" },
      { label: "Flex" },
      { label: "Flex Grow" },
      { label: "Flex Shrink" },
      { label: "Order" },
      { label: "Grid Template Columns" },
      { label: "Grid Column Start / End" },
      { label: "Grid Template Rows" },
      { label: "Grid Row Start / End" },
      { label: "Grid Auto Flow" },
      { label: "Gap" },
      { label: "Justify Content" },
      { label: "Justify Items" },
      { label: "Justify Self" },
      { label: "Align Content" },
      { label: "Align Items" },
      { label: "Align Self" },
      { label: "Place Content" },
      { label: "Place Items" },
      { label: "Place Self" },
    ],
  },
  {
    title: "Spacing",
    items: [
      { label: "Padding" },
      { label: "Margin" },
      { label: "Space Between" },
    ],
  },
  {
    title: "Sizing",
    items: [
      { label: "Width" },
      { label: "Min-Width" },
      { label: "Max-Width" },
      { label: "Height" },
      { label: "Min-Height" },
      { label: "Max-Height" },
      { label: "Size" },
    ],
  },
  {
    title: "Typography",
    items: [
      { label: "Font Size" },
      { label: "Font Smoothing" },
      { label: "Font Style" },
      { label: "Font Weight" },
      { label: "Letter Spacing" },
      { label: "Line Clamp" },
      { label: "Line Height" },
      { label: "List Style Position" },
      { label: "List Style Type" },
      { label: "Text Align" },
      { label: "Text Color" },
      { label: "Text Decoration" },
      { label: "Text Decoration Color" },
      { label: "Text Decoration Style" },
      { label: "Text Decoration Thickness" },
      { label: "Text Underline Offset" },
      { label: "Text Transform" },
      { label: "Text Overflow" },
      { label: "Text Wrap" },
      { label: "Text Indent" },
      { label: "Text Shadow" },
      { label: "Vertical Align" },
      { label: "Whitespace" },
      { label: "Word Break" },
      { label: "Hyphens" },
    ],
  },
  {
    title: "Backgrounds",
    items: [
      { label: "Background Attachment" },
      { label: "Background Clip" },
      { label: "Background Color" },
      { label: "Background Origin" },
      { label: "Background Position" },
      { label: "Background Repeat" },
      { label: "Background Size" },
      { label: "Background Image" },
      { label: "Gradient Color Stops" },
    ],
  },
  {
    title: "Borders",
    items: [
      { label: "Border Radius" },
      { label: "Border Width" },
      { label: "Border Color" },
      { label: "Border Style" },
      { label: "Divide Width" },
      { label: "Divide Color" },
      { label: "Divide Style" },
      { label: "Outline Width" },
      { label: "Outline Color" },
      { label: "Outline Style" },
      { label: "Outline Offset" },
      { label: "Ring Width" },
      { label: "Ring Color" },
      { label: "Ring Offset Width" },
      { label: "Ring Offset Color" },
    ],
  },
  {
    title: "Effects",
    items: [
      { label: "Box Shadow" },
      { label: "Box Shadow Color" },
      { label: "Opacity" },
      { label: "Mix Blend Mode" },
      { label: "Background Blend Mode" },
    ],
  },
  {
    title: "Filters",
    items: [
      { label: "Blur" },
      { label: "Brightness" },
      { label: "Contrast" },
      { label: "Drop Shadow" },
      { label: "Grayscale" },
      { label: "Hue Rotate" },
      { label: "Invert" },
      { label: "Saturate" },
      { label: "Sepia" },
      { label: "Backdrop Blur" },
      { label: "Backdrop Brightness" },
      { label: "Backdrop Contrast" },
      { label: "Backdrop Grayscale" },
      { label: "Backdrop Hue Rotate" },
      { label: "Backdrop Invert" },
      { label: "Backdrop Opacity" },
      { label: "Backdrop Saturate" },
      { label: "Backdrop Sepia" },
    ],
  },
  {
    title: "Tables",
    items: [
      { label: "Border Collapse" },
      { label: "Border Spacing" },
      { label: "Table Layout" },
      { label: "Caption Side" },
    ],
  },
  {
    title: "Transforms",
    items: [
      { label: "Scale" },
      { label: "Rotate" },
      { label: "Translate" },
      { label: "Skew" },
      { label: "Transform Origin" },
    ],
  },
  {
    title: "Interactivity",
    items: [
      { label: "Accent Color" },
      { label: "Appearance" },
      { label: "Cursor" },
      { label: "Caret Color" },
      { label: "Pointer Events" },
      { label: "Resize" },
      { label: "Scroll Margin" },
      { label: "Scroll Padding" },
      { label: "Scroll Snap Align" },
      { label: "Scroll Snap Stop" },
      { label: "Scroll Snap Type" },
      { label: "Touch Action" },
      { label: "User Select" },
    ],
  },
  {
    title: "SVG",
    items: [{ label: "Fill" }, { label: "Stroke" }, { label: "Stroke Width" }],
  },
];

export default menus;
