const menus = [
  {
    title: "Layout",
    items: [
      { label: "Box Sizing" },
      { label: "Display" },
      { label: "Floats" },
      { label: "Clear" },
      { label: "Object Fit" },
      { label: "Object Position" },
      { label: "Overflow" },
      { label: "Overscroll Behavior" },
      { label: "Position" },
      { label: "Top Right Bottom Left" },
      { label: "Visibility" },
      { label: "Z-Index" },
    ],
  },
  {
    title: "Flexbox",
    items: [
      { label: "Flex Direction" },
      { label: "Flex Wrap" },
      { label: "Flex" },
      { label: "Flex Grow" },
      { label: "Flex Shrink" },
      { label: "Order" },
    ],
  },
  {
    title: "Grid",
    items: [
      { label: "Grid Template Columns" },
      { label: "Grid Column Start End" },
      { label: "Grid Template Rows" },
      { label: "Grid Row Start End" },
      { label: "Grid Auto Flow" },
      { label: "Gap" },
    ],
  },
  {
    title: "Box Alignment",
    items: [
      { label: "Justify Content" },
      { label: "Justify Items" },
      { label: "Justify Self" },
      { label: "Align Content" },
      { label: "Align Items" },
      { label: "Align Self" },
      { label: "Place Content" },
      { label: "Place Items" },
      { label: "Place Self" },
    ],
  },
  {
    title: "Spacing",
    items: [
      { label: "Padding" },
      { label: "Margin" },
      { label: "Space Between" },
    ],
  },
  {
    title: "Sizing",
    items: [
      { label: "Width" },
      { label: "Min-Width" },
      { label: "Max-Width" },
      { label: "Height" },
      { label: "Min-Height" },
      { label: "Max-Height" },
    ],
  },
  {
    title: "Typography",
    items: [
      { label: "Font Size" },
      { label: "Font Smoothing" },
      { label: "Font Style" },
      { label: "Font Weight" },
      { label: "Letter Spacing" },
      { label: "Line Height" },
      { label: "List Style Type" },
      { label: "List Style Position" },
      { label: "Placeholder Color" },
      { label: "Placeholder Opacity" },
      { label: "Text Align" },
      { label: "Text Color" },
      { label: "Text Opacity" },
      { label: "Text Decoration" },
      { label: "Text Transform" },
      { label: "Vertical Align" },
      { label: "Whitespace" },
      { label: "Word Break" },
    ],
  },
  {
    title: "Backgrounds",
    items: [
      { label: "Background Attachment" },
      { label: "Background Clip" },
      { label: "Background Color" },
      { label: "Background Opacity" },
      { label: "Background Position" },
      { label: "Background Repeat" },
      { label: "Background Size" },
      { label: "Background Image" },
      { label: "Gradient Color Stops" },
    ],
  },
  {
    title: "Borders",
    items: [
      { label: "Border Radius" },
      { label: "Border Width" },
      { label: "Border Color" },
      { label: "Border Opacity" },
      { label: "Border Style" },
      { label: "Divide Width" },
      { label: "Divide Color" },
      { label: "Divide Opacity" },
      { label: "Divide Style" },
    ],
  },
  {
    title: "Tables",
    items: [{ label: "Border Collapse" }, { label: "Table Layout" }],
  },
  {
    title: "Effects",
    items: [{ label: "Box Shadow" }, { label: "Opacity" }],
  },
  {
    title: "Interactivity",
    items: [
      { label: "Appearance" },
      { label: "Cursor" },
      { label: "Outline" },
      { label: "Pointer Events" },
      { label: "Resize" },
      { label: "User Select" },
    ],
  },
];

export default menus;
